### ISSUE TITLE
Element-id attribute doesn't work.

### ISSUE THREAD

**Issue by umair-khanzada** [gilf/ngPrint#11]
Hi,
i am using ngPrint directive in my case `print-element-id="id-of-element"` doesn't works.
its print whole view instead of element view.

**Comment by gilf** [comment]
Hi,
Can you be more specific?
Where did you put the element-print-id?
Are you using the directive's CSS?

**Comment by umair-khanzada** [comment]
no i am not using directive css.
my code:
`<ul id="printThisElement"  ng-repeat="thing in Things">
        <li>
          <a >{{thing.name}}
            <button type="button" class="close" ng-click="deleteThing(thing)">&times;</button>
          </a>
        </li>
</ul>
<button class="btn btn-primary" ng-print print-element-id="printThisElement"><i class="fa fa-print"></i> Print</button>
`

**Comment by gilf** [comment]
Please use the ngPrint.css as part of your app or things won't work.
