### ISSUE TITLE
Printing Object Twice

### ISSUE THREAD

**Issue by ChrisReddickClarity** [gilf/ngPrint#12]
Just installed your directive and while I am getting a print view, the div that it's supposed to print is being included twice (in a direct stack on top of each other).

**Comment by gilf** [comment]
Can't reproduce your issue so can you explain how you used the directive or supply more information?

**Comment by ChrisReddickClarity** [comment]
Sorry about the delay, the mailbox for this account isn't directly monitored so I don't tend to get notifications right away.

What I eventually had to do was to remove the print div that it creates in order to prevent duplication. Eventually, my front end team member solved our printing needs via a different method and we removed ngPrint.
