### ISSUE TITLE
Prints the whole document and not the just the print section

### ISSUE THREAD

**Issue by rjain-pivotal** [gilf/ngPrint#5]
The code appends the printSection to the whole document Dom and hence it prints the whole document, just not the div section. 
`
       var printSection = document.getElementById('printSection');

```
    // if there is no printing section, create one
    if (!printSection) {
        printSection = document.createElement('div');
        printSection.id = 'printSection';
        document.body.appendChild(printSection);
    }
```

`

**Comment by gilf** [comment]
Did you use the ngPrint.css file? 
It should add a media query that shows only the print section when printing.

**Comment by javobal** [comment]
Why is it printing the print button in the plunker example?
![captura de pantalla 2016-11-07 a la s 12 34 36 p m](https://cloud.githubusercontent.com/assets/6923752/20070586/99d26894-a4e6-11e6-9a3d-5aa5d7f72ec3.png)

UPDATE:

i modified this part in the css to avoid printing the button

@media print {
    body \* {
        visibility:hidden;
    }

```
#printSection, #printSection * {
    display: inline;
    visibility: visible; 
}
```
