### ISSUE TITLE
table not displaying properly

### ISSUE THREAD

**Issue by nasr18** [gilf/ngPrint#6]
Everything looks good, except `table`. How do i fix this??

![screenshot from 2016-07-12 17 58 51](https://cloud.githubusercontent.com/assets/7514936/16766906/542f83be-485a-11e6-909d-16d3632b0807.png)

@gilf  @alimalik91

**Comment by gilf** [comment]
Try to use a print media query to style your table

**Comment by nasr18** [comment]
i did. but not working.

**Comment by gilf** [comment]
@nasr18 from the image you provided it looks like the table height is set to a very small value. As I wrote, try to style the table in the print media query. For example, something such as:
`@media print { 
    #printSection table {
      height: 100%;      
    }
}` 

I hope that it will help you.

**Comment by nasr18** [comment]
ok will try.

**Comment by ranamateenft** [comment]
same issue i am facing please help me

**Comment by raszkiewicz** [comment]
Issue with tables is still there

**Comment by DakotaWray2** [comment]
This problem persists and is definitely not a closed issue. It pretty much renders this repository unusable for many use cases.
