### ISSUE TITLE
AngulaJS view with ngDialog

### ISSUE THREAD

**Issue by RupenAnjaria** [gilf/ngPrint#8]
This is great directive. I am able to print the ngDialog however, it misses other styles. I need to print this with bootstrap and other css files that we are using in application.

Any ideal on how to integrate other style sheets with this directive?

**Comment by gilf** [comment]
The directive implementation is build with the help of print media query.
You can try to add your missing style into a print media query (see the example in the ngPrint css) as well.
Let me know if it helped.

**Comment by RupenAnjaria** [comment]
the issue is that they are not simple css styles. It is bootstrap, and have lots of content. I tried adding media='all' in all the css link - but it didn't work.

**Comment by joelcdoyle** [comment]
I had similar issues rendering tables in print preview, but as @gilf says, all you have to do is make changes to the print media query. Yes, bootstrap does have lots of styles, but the print media query only makes a few changes (really only one), that effects the page style, particularly:

```
@media print {
    #printSection, #printSection * {
        display: inline;
    }
}
```

for all elements within the print preview. But you are not tied to this, and you can change it. This is not an issue with ngPrint. Most browsers do not print background images, colors, etc. As you can see if you try to print Bootstrap's webpage: http://getbootstrap.com/css/
Many styles are omitted.

**Comment by RupenAnjaria** [comment]
When we say " print media query" is it same as updating all the styles include with media='all'? e.g. Currently the style sheets are included as below:

`<link rel="stylesheet" href="css/bootstrap.css"  >`

Are you saying that changing this to below should fix the issue?

`<link rel="stylesheet" href="css/bootstrap.css" **media='all'**>`

**Comment by joelcdoyle** [comment]
No, We're not saying that at all. "print media query" is referring to this statement in the included `ngPrint.css` file:

```
@media screen {
    #printSection {
        display: none;
    }
}

@media print {
    body * {
        display:none;
    }

    #printSection, #printSection * {
        display: inline;
    }

    #printSection {
        position:absolute;
        left:0;
        top:0;
    }
}
```

You will need to modify these styles or create your own styles for this print media query. Take a look at the source code in `ngPrint.js` to see what IDs and classes you need to be aware of and adjust your styles accordingly.

**Comment by RupenAnjaria** [comment]
I look at the code (both ngPrint.js and ngPrint.css). As per my understanding, ngPrint creates an element with id printSection and clones all the targeted elements to this element. While printing, body is set display none and print section is made visible. 

However, the issue is that my elements have bootstrap styles and I just wanted them to be printed as how it is shown on screen. To achieve this, I just copied entire bootstrap css in ngPrint.css file, under "@media print" section. It does improve the view, but still the bootstraps is not applied.

For example, my element is like "< div class='row' >..some content.. < / div >". Are you  saying that we need to write our own class "row" for printing specification (as bootstrap styles will not be applied)?

**Comment by joelcdoyle** [comment]
The point i'm trying to make is that Bootstrap defines it's own print styles:
https://github.com/twbs/bootstrap/blob/13e4348dfd78c0f1a28d5a108a4ec4f55de1271a/dist/css/bootstrap.css#L239
You would have to override those styles to get what you want.

In addition, everything inside of the `#printSection` has `display: inline` applied to it. If you remove that part of the css then you will have default Bootstrap behavior when printing. It is no different than printing Bootstrap elements without ngPrint

**Comment by vreljanski** [comment]
Hey it works well on a really old POS printer. Now it prints it using drivers and preset baud or those rates that makes it print kinda slower than the desktop direct eps/pos command sending app.

Sending POS/EPS directly to the printer using port somehow? Bypassing drivers? Or setting baud rates individually on some sort of Generic Driver?

**Comment by RupenAnjaria** [comment]
Thank you Joel. I tried commenting printSection, however I think we also have to comment display:none inside "body *" for print media. As otherwise, it is printing a blank page.

I understand that Bootstrap has print css define, but the page that I am trying to print is very odd (kind of breaking many things) while printing. So, I am not sure where to fix.
