### ISSUE TITLE
Print Section Not Clearing After Print

### ISSUE THREAD

**Issue by joelcdoyle** [gilf/ngPrint#9]
I'm testing in Chrome. If I print or cancel the print window, `window.onafterprint` is never called.
~~I suggest modifying the code with some of these tips:~~
http://stackoverflow.com/questions/13598790/onbeforeprint-and-onafterprint-is-not-working-in-chrome-and-ie
~~Or here:~~
https://www.tjvantoll.com/2012/06/15/detecting-print-requests-with-javascript/

This can actually be solved easily by just clearing the innerHTML just before getting the element by id on line 18.

**Comment by gilf** [comment]
Hi,

First of all, 10x for finding an issue. 
I added the print media query check to support browsers that don't include the afterprint event and include media query support. 
In previous versions the printElement function did clear the printElement before attaching the cloned element so it still works. On the other hand, the media query is also a solution that I think we need to support.
